title: Catch a scoop
hero_image: images/banner.png
description: Catch falling ice-cream scoops and stack them on a cone.
listed: false
pdf: false
steps:
  - title: Step 1
    completion:
      - engaged
  - title: Step 2
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
  - title: Step 7
  - title: Step 8
  - title: Step 9
  - title: Step 10
    completion:
      - internal
  - title: Step 11
    challenge: true
    completion:
      - external
